name: Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ear/target/java-eap-app.ear
    - uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/login-action@v1
      with:
        registry: registry.redhat.io
        username: ${{ secrets.RH_REGISTRY_USERNAME }}
        password: ${{ secrets.RH_REGISTRY_PASSWORD }}
    - run: docker tag $(./build-docker-image.sh) docker.pkg.github.com/maja-nord/java-eap-app/java-eap-app
    - run: docker push docker.pkg.github.com/maja-nord/java-eap-app/java-eap-app